### ISSUE TITLE
Change License from GPLv2

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/cordova-plugin-chromecast#19]
Since this project is now being used in more than just an Android app, it is pretty important that we re-license it.

I don’t know about Cordova specifics with linking this plug-in, so I will start with an understanding that this is provided with any app that uses it.

Under the general terms of the GPLv2, distribution on the Apple App Store is not technically permitted. There are various reasons, and the FSF covers some [here](https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement).

Technically, we have been given permission from @acidhax upstream to use the code as we see fit (see https://github.com/videostream/cordova-chromecast/issues/62) and so @joshuaboniface added the GPLv2 (see https://github.com/jellyfin/cordova-plugin-chromecast/commit/57ad1b707f5d788252092d57379690e1aa79d33a) as we believed that would be our only use at the time.

In order to make wider distribution more permissible, I propose that we re-license this library under a dual license. We will most likely follow the example set by VLC and choose a dual GPLv3/MPLv2 approach, but I am open to other suggestions.

In addition, to complete this process, we will need the permission of any contributors up to this point. I will tag them in a separate comment.

**Comment by sparky8251** [comment]
GPLv3/MPLv2 for me.

**Comment by anthonylavado** [comment]
@emilsas @joshuaboniface @froghut @dkanada @vitorsemeano After reviewing my original message above this, pending approval by the Jellyfin Core Team, do you consent to changing the license of this repo to a dual GPLv3/MPLv2?

For reference purposes:
* GPLv3 - https://spdx.org/licenses/GPL-3.0-only.html
* MPLv2 - https://spdx.org/licenses/MPL-2.0.html

Tracking:
- [x] JoshuaBoniface
- [x] Emilsas
- [x] Froghut
- [x] Dkanada
- [x] VitorSemano
- [x] nvllsvm

**Comment by emilsas** [comment]
For me it's ok!

**Comment by vitorsemeano** [comment]
All good for me.

**Comment by dkanada** [comment]
I am fine with those choices.

**Comment by Sel-en-ium** [comment]
Hello!  
I am considering using this plugin in my Cordova project.  I would be distributing my app to the google and apple stores.  
I would of course leave any changes I made to the plugin public on my fork.  (And maybe submit a pull request if the quality was good enough :p).
I just spent 2.5 hours trying to understand these licenses.  (I really just can't get it. >.<)

I have a couple questions. maybe you guys can answer them?

**1)** If I include this plugin can I still safely distribute to the app stores?
**2)** If I include this plugin does that mean I have to make my entire project's source open source? (Or give it to anyone who asks?)
**3)** Do I need to include license files somewhere in particular?  (Like on a page in my app?)

Edit:
**4)** After reading so. much. more.  It sounds like GPL would mean I have to release my app's source code?  

Assuming my understanding above is correct, it kind of seems like GPL might be inappropriate for Cordova plugin?  It will make prohibitive for most people to use (and hence work on).
Based on [acidhax's post](https://github.com/videostream/cordova-chromecast/issues/62#issuecomment-457255100) I don't think their intent was to have it be that restrictive (I could be wrong).  Obviously, you guys have put in a lot of work, so your intent matters a lot now too.

**5)** It seems that most plugins use the Apache 2.0 License.  Would it make sense to use this?
Or is MPL2 pretty similar?

**6)** The dual license also confuses me. :(  
Does that mean both licenses apply simultaneously?  (what about when they conflict?)
Or do they apply in different circumstances?  (Which circumstance?)
Or do I just get to choose which one I want to follow?  (What is the point in having the more restrictive license then?) 

Edit Edit:
Sorry it went on so long.  I have lots of questions after all my reading. >.<

**Comment by anthonylavado** [comment]
Hi @Sel-en-ium!

I'll do my best to help you understand here. The key thing to understand is that with a Dual License, you get to **choose which one applies**. This is why we have chosen this method.

----

>1) If I include this plugin can I still safely distribute to the app stores?

Yes.


>2) If I include this plugin does that mean I have to make my entire project's source open source? (Or give it to anyone who asks?)

Not necessarily. You get to choose whether you use it as MPL or GPL. If you choose MPL, then only these files (and any changes you make to them) must be available. You must also keep a notice of attribution, like seen here: https://www.mozilla.org/en-US/MPL/headers/


>3) Do I need to include license files somewhere in particular? (Like on a page in my app?)

They should be with the source code, or if not possible, in a LICENSE file. In the final app, a mention in the About/Credits screen is appropriate.


>4) After reading so. much. more. It sounds like GPL would mean I have to release my app's source code?

That's correct. If you _choose_ to take it under the GPL, then your "larger work" (your final app), must have its source code available. The GPL is "viral", so when it comes in to play, it changes everything it touches. _(Be sure to check the license on any other modules you might use! If any one of them is only GPL, the whole project could become GPL.)_


>Assuming my understanding above is correct, it kind of seems like GPL might be inappropriate for Cordova plugin? It will make prohibitive...

It depends. Some people feel very strongly about free software, and this gives them the chance to keep that alive (I'll explain why later). We also want to give people flexibility, which is why the MPL is an option as well. 


>5) It seems that most plugins use the Apache 2.0 License. Would it make sense to use this?
Or is MPL2 pretty similar?

MPL2 is pretty similar here. The main difference is that Apache 2.0 doesn't require you to share your source. We felt it was important that if you build on it, you should share back. The MPL option enforces this, at least for this part of the code in your app.

>6 Does that mean both licenses apply simultaneously? (What about when they conflict?)

Yes and no. Both licenses must stay in the file, but you get to choose which way it goes with your project. In this way, they do not conflict.

>Or do they apply in different circumstances? (Which circumstance?)

Nope. This just gives you extra flexibility.

>Or do I just get to choose which one I want to follow? 

Yes. You get to choose which one you want to follow, but it should stay licensed the same. You could "take out" the MPL, but then it becomes GPL, and then your whole program becomes GPL. The MPL, at a minimum, must stay.

>(What is the point in having the more restrictive license then?)

Consider this -  You work really hard on making improvements to this code. You think you've added some great new feature, and you're proud to share it with the world. You hope other people have a chance to use it, and make great things with it. Now, consider that it is only GPL licensed.

In most normal cases, this is good! Your work can be used, and anywhere it is used must share their whole source code as well. You're happy with this choice, because it forces them to give back, and possibly way more than they used. Again, this is good. Some people feel very strongly about this, and this lets them enforce that.

Now, a big company sees the impact this code is making, and sees that this code could be useful. They'd love to use it in their new program "XYZ 2019". Their team looks at the GPL only license, and instead decides that they'll pass. They won't use the code, because it would force them to give away their whole program. Just because they added the one module.

By having the MPL as an option, they can choose to "use that license" when they add it to their program. This means they can include it in "XYZ 2019", and they only have to do two things:
* Share back any changes they make to the module
* Provide some credit notice in the program

Their team looks at it, and decides that it's perfect. They will use the code, because they don't have to give away their whole program when doing so. Since they start using the code, they see a couple of opportunities to fix it up, make some pieces better, faster, more reliable. Because the MPL is used at a minimum, they must share back these changes. That's fine for them, because at least it's not their whole program. You get to see these changes online (or maybe they submit a Pull Request). This is wonderful! Everyone wins.

If we didn't choose the dual license option, the second scenario might never happen. For a module like this that many people could potentially benefit from, we felt that it was important enough to let more people use it, but that they should give back any improvements/changes they make.

Does that help? 


_As a side note:
GPL would have allowed you to distribute only on the Google Play Store, and only without DRM enabled on the App. The GPL is incompatible with the way the Apple App Store works. The MPL does not have this restriction, which was another important reason in choosing this dual license setup._

**Comment by Sel-en-ium** [comment]
Wow!  Thank you!  This may be the best answer I have ever received to a multi-part question!

I have checked all the other plugins I am using.  They are either Apache 2.0 or unlicensed.  I will ask the latter if they would be okay with adding a license (Apache 2.0 or MPL2).

I would consider it very poor sportsmanship not share changes and improvements made to an open source project.  So I like MPL2.  Particularly for this type of project (library/plugin).  The additional freedom of Apache may be nice for other types projects though.

Thank you for all the clarification.  I really liked the examples as well.  (Like I said, really great answer!)  (This is going to be a permanent bookmark for me probably. :p)

**Comment by sparky8251** [comment]
I think the biggest draw of the Apache2 is laziness. You aren't obligated to give back, which means you don't have to make any of your source available and certainly don't need to feel obligated to even attempt getting your changes upstreamed. You can just take it and go to town without having to deal with anything else.

I agree with your sentiments about the MPL and praise of @anthonylavado's answer! Both really are great :)
