### ISSUE TITLE
metadata not correctly set on receiver / not implemented for all types

### ISSUE THREAD

**Issue by ghenry22** [jellyfin/cordova-plugin-chromecast#23]
Currently on the generic metadata type is supported in the native code, while we can set the other types (movie, musictrack etc) in javascript and it gets passed through the native code checked if the metadata type is generic and if not ignores it.

However, even when the metadata type is generic it is still not populated on the receiver.

Same implementation limit and issue present on iOS and Android (so at least they're consistent!).

Need to investigate why metadata isn't being sent to the receiver and fix for the generic type.

Need to implement the other supported metadata types once the first issue is resolved.

**Comment by ghenry22** [comment]
Upon some investigation:

On iOS:
when loadMedia is called the metadata object is incorrectly cast and will always return nil so metadata will never be processed (any cannot be cast to Data).

see line 144 of Chromecast.swift
`let metadata = command.arguments[7] as? Data ?? Data()`
needs to be changed to:
`let metadata = (try? JSONSerialization.data(withJSONObject: command.arguments[7], options: [])) ?? Data()`

the same needs to be done for textTrackStyle or it will have the same issue

This gets metadata being passed through and set at least.

There is still an issue with the images object, in CastUtilities.swift where images are processed in the buildMetadata it will similarly always return nil when casting to type Data like this.

However, even ignoring images and just testing with the title and subtitle values being set I still don't see them on device for some reason, but it's a small step.

@emilsas - you know this code better than me, any chance you have time to take a look?

**Comment by emilsas** [comment]
Thanks @ghenry22 I will review this issue.

**Comment by ghenry22** [comment]
@emilsas what I have put above will fix the metadata and texttrackstyle always being nil.

It raises the question though, do we even need to cast to data just to cast back to dict a moment later.  Why not just cast it directly to a dict and then pass that.

But still need to investigate why metadata is not being set on the receiver.

For the images I haven't looked into why it is missing them yet, the let if statement for determining if images exist  always fails, it may be a similar thing where it is being cast to a data type but failing silently but I am not sure.

If we can get metadata properly set on the one generic case I will add all the handling for the other metadata types, I already wrote it for my old chromecastios plugin anyway.

**Comment by ghenry22** [comment]
On further investigation Android is correctly setting metadata, it just needs to be updated to handle the different metadata types, I will do this.

iOS is not setting the metadata even after getting it properly passed to the metadatabuilder function, need @emilsas to take a look at that and once fixed I can roll out the extra metadata types.

**Comment by ghenry22** [comment]
@emilsas any chance you could take a look into why metadata isn't being sent to the receiver on iOS?

**Comment by emilsas** [comment]
@ghenry22 sorry for the delay. I was very busy with other stuff. In this week I will review this issue.

**Comment by ghenry22** [comment]
@emilsas thanks excellent, I can help to test if needed.

**Comment by Lindsay-Needs-Sleep** [comment]
@ghenry22   Would you be able to provide a sample piece of code that uses this feature?  (and it's expected outcomes)
I would be glad to write a test from that and fix it on Android.

**Comment by Lindsay-Needs-Sleep** [comment]
I believe I have fixed this for Android on 1.0.0.

**Comment by rongchaua** [comment]
@Lindsay-Needs-Sleep : I'm using version 1.0.0 for Android

![image](https://user-images.githubusercontent.com/6661713/66255278-2429e180-e782-11e9-88f5-1e9275da7e16.png)

And i set the metadata as following

![image](https://user-images.githubusercontent.com/6661713/66255272-14120200-e782-11e9-93a3-3277374c99bf.png)

None of metadata values is shown on cast device. Can you please take a look again?

**Comment by Lindsay-Needs-Sleep** [comment]
Hi @rongchaua 

I have updated the metadata a bit.  I think it will probably fix it for you.

**Below may be irrelevant:**

But, I am not sure that you are actually getting the 1.0.0 version.  (I'm not familiar with the first image you included.)
1.0.0 is currently on the **1.0.0 branch** of [my fork](https://github.com/miloproductionsinc/cordova-plugin-chromecast/tree/1.0.0)  of the repo (it is not on jellyfin yet).  

Also, I'm not sure if the "@1.0.0" syntax will work either.  If "@" refers to the package.json version then it will probably be retrieving an older version of the code I have been working on.  I labeled the version in package.json as "1.0.0" when starting, but that was improper, so it is currently "1.0.0-dev".  (I have not added any tags, and I believe that is what "@" normally refers.)

You should be able add the current 1.0.0 version of the plugin with:

```
cordova plugin add https://github.com/miloproductionsinc/cordova-plugin-chromecast.git#1.0.0
```
