### ISSUE TITLE
CC License for chromecast documentation

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [jellyfin/cordova-plugin-chromecast#24]
I noticed that the function documentation in chrome.cast.js is basically just a copy and paste from the official chromecast docs.

eg. chrome.cast.media.LoadRequest
https://developers.google.com/cast/docs/reference/chrome/chrome.cast.media.LoadRequest

At the bottom of the page it says:
"Creative Commons Attribution 4.0 License,Except as otherwise noted, the content of this page is licensed under the Creative Commons Attribution 4.0 License, and code samples are licensed under the Apache 2.0 License."

There site policies also give instructions on how to provide attribution:
https://developers.google.com/terms/site-policies#attribution

How this would apply in this case?

(I thought there was a thread about tracking license info for modules on here but I can't seem to find it... Maybe I was dreaming?)

**Comment by anthonylavado** [comment]
I'm not seeing an exact copy/paste as you're mentioning? For reference, here are the lines I'm looking at:
https://github.com/jellyfin/cordova-plugin-chromecast/blob/7ac100f27fb126304d3a22f20be74cdbb5461da0/chrome.cast.js#L763-L768

At any rate, if there are any direct copies, we simply need to add the attribution notice and we're good to go.

For the other issue you were mentioning, it's on the main repo: https://github.com/jellyfin/jellyfin/issues/610

**Comment by Lindsay-Needs-Sleep** [comment]
Oops, I think I pasted the wrong link!

For those lines, (763-768),  you should be able to see that the parameter descriptions are copy/pastes from the parameter descriptions here:
https://developers.google.com/cast/docs/reference/chrome/chrome.cast.Session#loadMedia

So I should just put the attribution notice in the file?

(Thank you the issue link!  No wonder I couldn't find it.  Not sure how I ever wound up looking at the main repo in the first place! :p)

**Comment by anthonylavado** [comment]
@Lindsay-Needs-Sleep Ah okay! That makes more sense. Yeah, we should probably put the attibution notice in and then it should all be clear. CC-4.0 doesn't preclude GPLv3/MPLv2, so it all works in the end.
