### ISSUE TITLE
OnMessage Doesn’t Handle Single Quotes Correctly

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/cordova-plugin-chromecast#34]
In https://github.com/jellyfin/jellyfin-web/issues/440, it was discovered that playing a file with an apostrophe/single quote in its name would cause the Jellyfin Android app to lose control of the ChromeCast.

Through further review, it appears that this line presents an issue:
https://github.com/jellyfin/cordova-plugin-chromecast/blob/c1ba3e7b25ca1097efb21bef0baf19b0d6801971/src/android/Chromecast.java#L809

The Session ID is a GUID, and the namespace in this case is `urn:x-cast:com.ConnectSDK`. The message is where the concern comes in.

Since the message will contain JSON, a single quote in a value (such as media title) is valid. However, the larger string in Java is wrapped in single quotes, so this causes the string to be terminated early.

We should identify the best way to handle unexpected single quotes in the message, or wrap this in a way where single quotes won’t interfere.

**Comment by anthonylavado** [comment]
I don't know Java or Cordova at all. Would this help?

Going from
https://github.com/jellyfin/cordova-plugin-chromecast/blob/c1ba3e7b25ca1097efb21bef0baf19b0d6801971/src/android/Chromecast.java#L807-L810

to 

```java
	@Override
	public void onMessage(ChromecastSession session, String namespace, JSONObject message) {
		sendJavascript("chrome.cast._.onMessage('" + session.getSessionId() + "', '" + namespace + "', '" + message.toString() + "')");
	}
```

**Comment by anthonylavado** [comment]
Either @lewazo or @lindsay-needs-sleep, any idea if this would help our issue?

**Comment by lewazo** [comment]
Yeah I was planning on looking a this issue and your proposed changes today.

**Comment by Lindsay-Needs-Sleep** [comment]
I was planning on looking at this after I’ve got 1.0 satisfactory, but that will probably be awhile, so thanks @lewazo!

Any chance that anyone can post some sample code that I can turn into a test later?
(I’m not familiar with the sendMessage functionality yet).

**Comment by lewazo** [comment]
So using JSONObject wouldn't solve the problem since it'll still output an unescaped string.

The solution here would be to let JavaScript itself handle the escaping like this

```java
@Override
	public void onMessage(ChromecastSession session, String namespace, String message) {
		sendJavascript("chrome.cast._.onMessage('" + session.getSessionId() + "', '" + namespace + "', JSON.stringify(" + message + "))");
	}
```

These changes solves the problem reported in https://github.com/jellyfin/jellyfin-web/issues/440.

**Comment by thornbill** [comment]
I believe this would encounter the same issue for any message containing `"`.

**Comment by lewazo** [comment]
Nevermind, your prosposed changes works just fine @anthonylavado, it's just Chrome who misled me since he likes to not display the escape characters when outputing to the console, but the strings are indeed escaped.

Escaping the strings before sending to JS is of course better.

I submitted a PR with the required changes in order to implement the solution.

@thornbill It didn't since the string isn't wrapped in `"`, it's a literal.

**Comment by thornbill** [comment]
Oh right my bad. I should have looked at that closer.
