### ISSUE TITLE
1.0.0 refactor

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [jellyfin/cordova-plugin-chromecast#36]
The largest changes of this refactor are:

- [x] iOS, Android, and Chrome Desktop all work the same now!  (With a few caveats.)
All 3 will pass the same set of tests included in the plugin.

- [x] iOS and Android have `scanForRoutes`, `stopScan`, and `selectRoute` to replace `getRouteListElement`

- [x] iOS and Android still do not implement the full chromecast API, but a few more have been added, and existing ones have been made to match chrome desktop behavior.

**Bug Fixes**: 
- Fixes #17 (cancel should return error)
- Fixes #22 for Android (getRouteListElement() returns empty object) non-issue now
- Fixes #22 for iOS (getRouteListElement() returns empty object) non-issue now
- Fixes #23 Metadata not set
- Fixes #26 #27 (compile/dependancy error)
- Fixes #32 (duplicate routes are displayed)
- Fixes #36 (Because that is this issue :p)
- Fixes #43 (crash on requestSession)
- Fixes #41 remove deprecated `sendJavascript` usage
- Fixes #47 iOS crash
- Fixes #48 selectRoute crash
- Fixes #49 selectRoute silent fail
- Fixes #50 Switch to Mocha for tests
- Play audio files https://github.com/miloproductionsinc/cordova-plugin-chromecast/issues/3

**Improvements:**
- Upgraded to CAF v3, this got rid of a huge amount of deprecation notices.
- Added eslint tests to ensure uniform js code stlying
- Added a style checker for java
- Updated documentation on: how to run style checkers, how to run tests.
- Added a pull request template which instructions prospective pull requesters to run eslint and the tests
- Repaired and added to the existing tests enforcing chrome desktop SDK behavior.
- On app initialize you will receive any previously started+active session.  (This includes navigating to a new page, or force killing the app and re-loading.)
- Implemented startRouteScan and stopRouteScan to replace getRoutes ([see why](https://github.com/jellyfin/cordova-plugin-chromecast/issues/22#issuecomment-530773677))
- fixed selectRoute for Android 4.4.2
- Allow native error responses to send a json object "code" and "description" parameters in addition to just the error code string. 
- Implement basic queue functionality
- Tests can run on chrome desktop browser as well (with a couple stubs to enable missing functionality)
  - This is super useful because you can write tests and check that they work correctly on chrome first.  Which is very important when chrome's implementation is what we are implementing.
- Added a basic code example
- Updated readme with all kinds of instructions (differences between chrome, api list, plugin-specific api list, api usage example, support+quirks, setup, how to test, how to run formatting test)
- Added pull request template
- Added scripts to assist in enforcing code formatting for JS and Java

**Auto-tests**:
- initialize
    - receiverListener
    - sessionListener
- leaveSession
- stopSession
- loadMedia Video
- media.setVolume
- media.play
- media.pause
- media.stop
- session.setReceiverVolumeLevel
- session.setReceiverMuted
- requestSession
- cordova.startRouteScan
- cordova.stopRouteScan
- cordova.selectRoute
- MediaMetadata (All types with most of their special params)
- loadMedia Audio (Did not test playback controls)
- loadMedia Image
- load queue
- jump to queue item

**Manual Tests**:
- Start session, reload page, call initialize, do we get session again?
- Start session, force kill app, restart app, do we get session again?
- Start session, join session with additional device, **leave** session on original, session still continues?, force kill and restart original device, original device should not rejoin the session automatically.
- for session Leave: probably need to join the session from an additional device,then leave the session, restart app, does it rejoin the session? (it shouldn't) (pre-req rejoin on restart must work)
- for loadmedia from external sender: start session on device, join session on other device, loadmedia from other device, is session.addMediaListener triggered?
- for external exit: Start session, kill session with other device, requestSession should show the the join dialog, not stopCasting

**Comment by Lindsay-Needs-Sleep** [comment]
My first question is:
Does anyone use ‘chrome.cast.getRouteListElement()’ method?
If no one does, I would like to skip it in my refactor because it is not strictly part of the chrome sdk.

Edit: Or, maybe if you use it, it might be worth switching to the default requestSession pop up?  The popUP accepts a theme, and I have a TODO which could allow the user to specify the theme via config.xml.  This would allow for custom styling.  (Or we could just give the option between “light” and “dark” to make it platform independent.)  I understand customizability is nice, but I think it is worth noting that big apps like youtube and netflix appear to use default popup (with a custom title for netflix).

This would be nice because then we could drop that functionality all together (which is kind of messy).

I have started on re-implementing this functionality, but it is buggy.  You are only allowed to join a route once per app lifecycle.  Additional attempts to join routes after the current cast session have ended result in a weird state where a cast session is started (you can see it on the tv), but it comes back as the “cast session could not be started due to timeout”, so you have no session to control.

What are all your thoughts? 
@anthonylavado @lewazo @emilsas (and others too I may not have included o.o)

**Comment by dkanada** [comment]
> Added eslint tests to ensure uniform code stlying.

I'd like to move this project from tabs to spaces at some point since all our other repos use four spaces for indentation.

> Upgraded to CAF v3, this got rid of a huge amount of deprecation notices.

I don't believe this has been done yet in the sibling repo. It has a [pull request](https://github.com/jellyfin/jellyfin-chromecast/pull/7) open to migrate to v3 but progress has mostly halted, so if you want to continue working on this I can open a new branch with @cvium's changes.

> Does anyone use ‘chrome.cast.getRouteListElement()’ method?

I haven't looked in a while but I think that's what jellyfin-web uses to build the list of devices. I agree we should remove it, but we should remove its usage in the web client first if that's the case.

**Comment by lewazo** [comment]
As I understand it, jellyfin-web does not use this plugin at all, it directly uses the Google SDK with their own `chrome.cast` object here https://github.com/jellyfin/jellyfin-web/blob/master/src/scripts/site.js#L348.

The web client never deals directly with the bookeeping of the routes since they are managed by the cast framework directly.

To answer your first question @Lindsay-Needs-Sleep I do not believe the Jellyfin project uses the getRouteListElement() method, since the jellyfin-android app is the only app using this plugin. But I'm a recent contributor so I might be clueless of other clients that might use it. Maybe AndroidTV? That would be surprising since it can run the native SDK (it does not uses cordova).

IMO, using the default, standard Android mediaChooserDialog is the way to go. It would make the bookeeping of routes way easier. And yes, this functionality is quite messy as it is.

**Comment by Lindsay-Needs-Sleep** [comment]
@dkanda and @lewazo 
Thanks for the feedback!

I won't worry about supporting `chrome.cast.getRouteListElement()` then. (That's a relief!)


@dkanada 
> > Added eslint tests to ensure uniform code styling.
> 
> I'd like to move this project from tabs to spaces at some point since all our other repos use four spaces for indentation.
> 
All of the js files have been styled to 4 space indentation.  The java files are tabs though (since they were already pretty consistently tabs).  I can change that as well.  It also seems to fit with the style used on other cordova plugins as well, so this makes sense.

> > Upgraded to CAF v3, this got rid of a huge amount of deprecation notices.
> 
> I don't believe this has been done yet in the sibling repo. It has a [pull request](https://github.com/jellyfin/jellyfin-chromecast/pull/7) open to migrate to v3 but progress has mostly halted, so if you want to continue working on this I can open a new branch with @cvium's changes.
> 
Unfortunately, the company I am working for doesn't use the jellyfin receiver, so I don't think I will be able to help here.  Perhaps once my changes are a little further along we can open a branch on this repo (eg. 1.0.0)?  Then include instructions in the master branch readme about how to install the newer version if desired.  This will allow other cordova dev's to more easily choose the version if they want?  I'm not sure what the best method is for supporting multiple major versions.  At lest until jellyfin is ready to update.

**Comment by Lindsay-Needs-Sleep** [comment]
My next question is(!):

Does anyone know of a publicly hosted video which provides a non-expiring, direct link to the mp4 stream?

The video link that was in the tests didn't work.  I added a very small video to the project for the tests, but it requires you start a server to host it (since the plugin does not support playing local files).  I would like to change this.  The extra step for testing will be annoying for other devs.

**Comment by anthonylavado** [comment]
@Lindsay-Needs-Sleep What kind of video stream do you need?

**Comment by Lindsay-Needs-Sleep** [comment]
Any kind that the plugin should support!  Doesn't matter to me!
Just something I can pass to `chrome.cast.media.MediaInfo(videoUrl, 'video/mp4')`

Unfortunately all the videos I have access to for work are private, so I can't use them.  I have tried extracting the mp4 link from youtube and vimeo videos using vlc player, but they have expiration dates.  I also don't have access to a server to properly host a video.

**Comment by Lindsay-Needs-Sleep** [comment]
I am also wondering where the most appropriate place is to log TODOs? (the kind of TODOs that I won't be able to get to for maybe months, but don't want to forget).  Should I open issues for each?  

eg. implement queues, deprecation notices, enable and satisfy java styling rules I temporarily disabled (because there were just way too many nit-picky ones and I just don't have that much time atm. >.<)

**Comment by anthonylavado** [comment]
Yeah, Issues are best.

I’ll see what I can do on the video URL space. Sounds like something from the Internet Archive would work.

**Comment by Lindsay-Needs-Sleep** [comment]
I think I will keep the top post as kind of progress tracker.  But so that we have history and conversations make sense, here is what I just updated it to:

I am working on a refactor that simplifies a few things and much more closely follows the behavior of the desktop chrome SDK.

Done:
- Upgraded to CAF v3, this got rid of a huge amount of deprecation notices.
- Fix #26 #27 (compile/dependancy error)
- Fix #32 (duplicate routes are displayed)
- Fix #17 (cancel should return error)
- Added eslint tests to ensure uniform js code stlying
- Added a style checker for java
- Updated documentation on: how to run style checkers, how to run tests.
- Added a pull request template which instructions prospective pull requesters to run eslint and the tests
- Repaired and added to the existing tests enforcing chrome desktop SDK behavior.
- Made the test chains terminate on error (jasmine is kind of terrible).
- On app initialize you will receive any previously started+active session.  (This includes navigating to a new page, or force killing the app and re-loading.)

Tests that need to be written:
- (manual test) Start session, force kill app, restart app, do we get session again?
- (manual test) Start session, join session with additional device, **leave** session on original, session still continues?, force kill and restart original device, original device should not rejoin the session automatically.
- (auto-ish) Everything else to do with media and playback.

Working on:
- Adding to the test suite as I fix features
- Confirming media functionality
- Remove getRoutes functionality (I just worked so hard on it, I am reluctant to remove now. :p)

Could use help on:
- Adding to the test suite.  It would be nice if someone could write a couple more tests for untested but used functionality.  (Since I don’t know which parts of the plugin everyone uses.)
- I have basically no experience with iOS, so all of that.  (Make sure it still works with slight javascript changes, and passes all the tests.)
- getting a hosted video url for tests
)

TODO later (for 1.0.0):
- finish confirming pre-existing functionality

TODO later (post 1.0.0)
- implement queues (maybe as 1.0.0?)
- #41 remove sendJavascript
- Maybe switch from jasmine tests to mocha.  (Mocha seems more intuitive to me.  And we wouldn't need to have these huge ugly test chains that are difficult to debug.)

Opinions?

**Comment by anthonylavado** [comment]
Tagging @emilsas and @ghenry22, who use the iOS side more. Any input?

**Comment by anthonylavado** [comment]
@Lindsay-Needs-Sleep There should be something you can use for testing here: https://archive.org/details/CosmosLaundromatFirstCycle

**Comment by Lindsay-Needs-Sleep** [comment]
(@anthonylavado Thanks for the link, the video works great! )

Here are changes made to first comment to reflect recent progress:

> Has good (provides decent coverage) tests:
> - initialize
>   - receiverListener
>   - sessionListener
> - leaveSession
> - stopSession
> - media.setVolume
> - session.setReceiverVolumeLevel
> - session.setReceiverMuted
> - requestSession
> - cordova.startRouteScan
> - cordova.stopRouteScan
> - cordova.selectRoute
> 
> Tests that need to be written/improved:
> - (manual test) Start session, force kill app, restart app, do we get session again?
> - (manual test) Start session, join session with additional device, **leave** session on original, session still continues?, force kill and restart original device, original device should not rejoin the session automatically.
> - loadMedia (what update listeners should be triggered, and with status changes?)
> - play (what update listeners should be triggered, and with status changes?)
> - pause (what update listeners should be triggered, and with status changes?)
> - stop (what update listeners should be triggered, and with status changes?)
> - messages (no tests at all)
> - (probably missing some others.  Load images or audio?)

**Comment by Lindsay-Needs-Sleep** [comment]
I think I have kind of changed my mind about the `getRoutes` functionality, here's why:

- It appears that at least some people are interested in the getRoutes function (#22) 
- I do think it could be nice for users who want to display with html to keep their app look consistent.
- It is useful for the automated tests.  Without it, there is no way to start a session without user interaction.
- I have already tested it and it is working (Might as well keep it right? :p)

@anthonylavado @lewazo What do you think?

**Comment by lewazo** [comment]
The freedom you get from being able to customize the dialog how you want using HTML and CSS is a very nice feature IMO. Like you said, it's already there and it works. Not much would need to be done in order to keep it working if modifications are done since it relies mostly on the routeAdded callback which is called directly by the framework.

Might as well keep it!

**Comment by anthonylavado** [comment]
@Lindsay-Needs-Sleep I would say @dkanada and/or @thornbill are the better resources to ask. They’ll know more towards our usage of the plug-in in the Jellyfin Android app.

**Comment by Lindsay-Needs-Sleep** [comment]
@lewazo I should mention that I have changed the getRoutes functionality to these functions instead: 
cordova.startRouteScan
cordova.stopRouteScan

The reasoning is here: https://github.com/jellyfin/cordova-plugin-chromecast/issues/22#issuecomment-530773677

**Comment by dkanada** [comment]
So you have definitely changed a lot of things, but it would still be great to have them all in master. Do you have a plan for that other than a huge pull request?

**Comment by Lindsay-Needs-Sleep** [comment]
Just a big pull request is all I was thinking.

I’m just not sure if I should create the pull request now or after iOS is complete. (Because iOS is definitely going to 100% broken after all my changes.)

My company has hired someone to get iOS up to speed.  But it is a lot of work.  I’m not sure if they would be open to assistance or not.  (Also depending on if assistance is available?)

I could start the pull request sooner as well if people want to be able start working off of this sooner.  I am definitely open to suggestions on how to proceed.

**Comment by dkanada** [comment]
If you could do some of the smaller items in separate PRs that might help get your changes through faster. Things like the testing framework change or the PR template should be easier to review. We might want to add a CI job here to build every PR before it gets merged, if you're familiar with Azure I can add the job to our pipeline.

**Comment by Lindsay-Needs-Sleep** [comment]
I don’t think I will have time to pull it all apart into different PRs.  

Pulling out the PR template wouldn’t be too bad.  But separating the test framework change would be huge, and would destroy the commit history, (which, in this case, could offer useful insight for answering future questions of “why was it done like this?”)

I am not familiar with Azure or implementing CI jobs.  That does sound like a good idea though!  
How would it handle testing a chromecast device though?  Only like the 1st 2 tests will pass without a valid chromecast on the network.  
The styling stuff should work though I guess! 
Or would it just test that plugin builds without errors for a cordova ios/android project?
