### ISSUE TITLE
'@objc' method name provides one argument name, but method has 0 parameters

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [jellyfin/cordova-plugin-chromecast#47]
I had [this same issue](https://github.com/miloproductionsinc/cordova-plugin-chromecast/issues/4) reported on my fork of the repo.  I just tried running iOS myself as well (from jellyfin's master) and got the same error.

From the original issue post: 

> Build failed with this error.
> 
> '@objc' method name provides one argument name, but method has 0 parameters in Chromecast.swift
> 
> @objc(checkReceiverAvailable:)
> ```
> @objc(checkReceiverAvailable:) 
> func checkReceiverAvailable() {
>    let sessionManager = GCKCastContext.sharedInstance().sessionManager
> 
>    if self.devicesAvailable.count > 0 || (sessionManager.currentSession != nil) {
>        self.sendJavascript(jsCommand: "chrome.cast._.receiverAvailable()")
>    } else {
>        self.sendJavascript(jsCommand: "chrome.cast._.receiverUnavailable()")
>    }
> 
>  }
> ```

I got this error while using cordova 9.0.0, ios platform 5.0.1, and xcode 10.2.2.

**Comment by emilsas** [comment]
Hi, in the PR #40 it's fixed

**Comment by Lindsay-Needs-Sleep** [comment]
Oh excellent!  Thanks!
