### ISSUE TITLE
cordova-plugin-chromecast/Chromecast.swift:1:8: error: no such module 'GoogleCast'

### ISSUE THREAD

**Issue by desmeit** [jellyfin/cordova-plugin-chromecast#55]
I got the following error:

`cordova-plugin-chromecast/Chromecast.swift:1:8: error: no such module 'GoogleCast'`

Maybe the dependencies are not installed correctly? But where can I download it and to which folder I have to copy it?

Thanks

**Comment by emilsas** [comment]
Hi @desmeit,
You need to be sure that you have installed cocoa-pods in your Mac. Because when you run **cordova platform add ios** or **cordova plugin add crodova-plugin-chromecast**, it runs **pod install**.

**Comment by desmeit** [comment]
@emilsas 
Thanks for your answer. cocoa-pods is installed. should I run `pod install` manually?
Do you have another idea? 

Thanks

**Comment by Lindsay-Needs-Sleep** [comment]
In your project, you can try this:

Deleted the folders: plugins, platforms, node_modules

run 
cordova prepare ios --verbose

I know cocoa pods gave me some trouble before.  verbose should help locate the source of the error.

**Comment by desmeit** [comment]
Sorry, but I cannot remove and recreate all plugins. This is a lot of work. ;-)

I run pod install. Now I have the following error:

```
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/XXX/Library/Developer/Xcode/DerivedData/XXX-cdnrowdvqvnybrhfiuvvrgsuejzl/Build/Intermediates.noindex/ArchiveIntermediates/XXX/IntermediateBuildFilesPath/XXX.build/Debug-iphoneos/Programm21.build/Script-ED08B2BD85AE36CF2B3D543F.sh
(1 failure)
xcodebuild: Command failed with exit code 65
```
I think I have to look for another plugin. This is not working for me, unfortunately.

**Comment by Lindsay-Needs-Sleep** [comment]
Well, you can try just removing and re-adding chromecast then:
`cordova plugin rm cordova-plugin-chromecast`

re-add with verbose:
`cordova plugin add cordova-plugin-chromecast --verbose`

**Comment by desmeit** [comment]
Thanks @Lindsay-Needs-Sleep 

I will try the new version.

**Comment by desmeit** [comment]
Now I have this error:

```
** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/XXX/Library/Developer/Xcode/DerivedData/XXX-cdnrowdvqvnybrhfiuvvrgsuejzl/Build/Intermediates.noindex/ArchiveIntermediates/XXX/IntermediateBuildFilesPath/XXX.build/Debug-iphoneos/XXX.build/Objects-normal/armv7/MLPChromecast.o XXX/Plugins/cordova-plugin-chromecast/MLPChromecast.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by Lindsay-Needs-Sleep** [comment]
It's really hard to say what is causing the problem.

(This issue)[https://github.com/ionic-team/ionic/issues/13445] sounds pretty similar.  
1) The first reporter was able to fix it by trying my (earlier suggestion)[https://github.com/jellyfin/cordova-plugin-chromecast/issues/55#issuecomment-581057099].
2) Another guy says you can try this:
`cd platforms/ios`
`pod install`

3) You could try creating an empty cordova project and add the plugin, see if that works.  (Will help to determine if it is your environment or your project.)

I've also read that a may be a permission issue.  So maybe you can make sure that no files require sudo permission.

**Comment by desmeit** [comment]
I tried all of it with no luck.

I have these 3 errors:

![Bildschirmfoto 2020-02-11 um 09 15 13](https://user-images.githubusercontent.com/9454529/74220139-11cf2f80-4caf-11ea-8358-6391f090ff1c.png)

**Comment by Lindsay-Needs-Sleep** [comment]
My mac experience is low.  I'm not sure what to do beyond googling those errors.  

I would probably try something like "cordova ios sandbox is not in sync with the Podfile.lock."

I did have some trouble along these lines (but that was too long ago).  I was able to find enough hints by searching for cordova/ios/pods/error/etc that I was able to muster through.  I did so many things though.  At some point I had to manually modify some (hidden-ish?) user setting files for xcode.  In the end, I wasn't sure what fixed my (many) problems.

I know that's not very helpful, sorry. >.<

**Comment by desmeit** [comment]
ok for IOS now I was able to install. I do not use cordova 9.0.0. because of that I have to install the pods through the old framework tag.

But now I try to initialize and I get the following error:

`error: {"code":"unknown","description":"api_not_initialized null","details":{}}`


My code:

```
 // File globals
       var _session;
       var _media;

                          
                          // use default app id
                          var appId = chrome.cast.media.DEFAULT_MEDIA_RECEIVER_APP_ID;
                          var apiConfig = new chrome.cast.ApiConfig(new chrome.cast.SessionRequest(appId), function sessionListener (session) {
                                                                    
                                                                    console.log("cast session: " + session);
                                                                    
                                  // The session listener is only called under the following conditions:
                                  // * will be called shortly chrome.cast.initialize is run
                                  // * if the device is already connected to a cast session
                                  // Basically, this is what allows you to re-use the same cast session
                                  // across different pages and after app restarts
                              }, function receiverListener (receiverAvailable) {
                                                                    console.log("cast receiverAvailable: " + receiverAvailable);
                                  // receiverAvailable is a boolean.
                                  // True = at least one chromecast device is available
                                  // False = No chromecast devices available
                                  // You can use this to determine if you want to show your chromecast icon
                              });

                          // initialize chromecast, this must be done before using other chromecast features
                          chrome.cast.initialize(apiConfig, function () {
                                                  console.log("cast initialize");
                              // Initialize complete
                              // Let's start casting
                              requestSession();
                          }, function (err) {
                                                 console.log("cast initialize error: " + JSON.stringify(err));
                              // Initialize failure
                          });
```

**Comment by Lindsay-Needs-Sleep** [comment]
@desmeit Sorry, I've been super busy.
Do you still need help with this?

You are probably seeing api_not_initialized because your script is running too soon.

I noticed the code you showed us is not wrapped with:
```
document.addEventListener("deviceready", function () {
  // start using the api!
  // All the code that uses "chrome.cast" should happen after "deviceready" event
});
```

If that isn't the case, let me know!
