### ISSUE TITLE
Amazon Fire Tv Stick cast?

### ISSUE THREAD

**Issue by Be4t5** [jellyfin/cordova-plugin-chromecast#60]
It would be awesome if this plugin could cast even to Amazon Fire Tv Stick device. Do you plan to implement something like that?
Thanks!

**Comment by Lindsay-Needs-Sleep** [comment]
Nope, sorry, I have no plan to implement that.
I think this plugin is very chromecast focused (and should stay that way imo). 

I'm not sure what the API's for Amazon Fire TV Stick are like... but even if it is similar, I think it might be best to create a separate Amazon Fire TV Stick plugin, then another plugin that utilizes/includes/depends on both the chromecast and amazon plugins and creates a unified interface.  This would help prevent the project from becoming a monolith.  And allow improvements to be submitted more easily by people who only care about 1 casting service.

If you want a plugin that supports multiple casting interfaces you should check out [Connect SDK](http://connectsdk.com/) (they even have a Cordova plugin).  
Originally, I tried using the plugin but I couldn't get it to work, and support seemed kind of dead, but just checking now, it looks like there has been some commit activity.  So maybe it has come back to life!

**Comment by Be4t5** [comment]
Thank you!
