### ISSUE TITLE
This plugin is not working in IOS

### ISSUE THREAD

**Issue by saddam0710** [jellyfin/cordova-plugin-chromecast#62]
Hi,

Right now I'm using `chrome.cast` object and it works for android but not in IOS.

Can you please help me.
Thanks in advance!

**Comment by saddam0710** [comment]
Hi,

After deleting all generated/builded code/files/folders

node_modules
platforms (perform ionic cordova platform rm android / ios first)
plugins
www


Reboot computer and reinstall the dependencies

npm i
ionic cordova platform add android / ios (will create the platform and install the plugins automatically)
ionic cordova run android / ios


Ant it working fine

**Comment by julianCast** [comment]
How did you import this plugin in Ionic @saddam0710 ?
Im' trying:
Install: `cordova plugin add https://github.com/jellyfin/cordova-plugin-chromecast.git`
 Use: `import * as Chrome from 'cordova-plugin-chromecast/www/chrome.cast';`

But a lot of errors such as 
`Module not found: Error: Can't resolve 'cordova-plugin-chromecast.EventEmitter'`

Thanks!
