### ISSUE TITLE
Does anyone use session.sendMessage?

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [jellyfin/cordova-plugin-chromecast#65]
I want to know if anyone uses this, and whether or not it actually works?

@anthonylavado @dkanada Jellyfin uses a custom receiver I believe, which seems to be the main reason to use sendMessage....  So just wondering if you guys are using it?  (even on the old version of cordova-plugin-chromecast)

**Comment by anthonylavado** [comment]
We're moving to a newer receiver soon, but let me dig in to this.

**Comment by Lindsay-Needs-Sleep** [comment]
Ty!  
If you do, can you include some samples of how you use it? 
I would like to write some tests for sendMessage.  (Especially if people are using it! :))
(Also, no rush at all!)

**Comment by Lindsay-Needs-Sleep** [comment]
I think since #64 option 4 is the best (which uses sendMessage), we will keep it.  And hopefully add tests for it one day.

Notes:
Tested sendMessage on Android, it appears to successfully send a message, but fails to recognize a success response (it always goes to error even when the command works).
Completely untested on iOS.
