### ISSUE TITLE
Error phonegap build GoogleCast/GoogleCast.h

### ISSUE THREAD

**Issue by Marthaarman** [jellyfin/cordova-plugin-chromecast#67]
The phonegap builder (for iOS) exits on the following error:

In file included from /project/xxx/Plugins/cordova-plugin-chromecast/MLPChromecast.m:5:
/project/xxx/Plugins/cordova-plugin-chromecast/MLPChromecast.h:6:9: fatal error: 'GoogleCast/GoogleCast.h' file not found
#import <GoogleCast/GoogleCast.h>

I import the plugin using:
`<plugin source="git" spec="https://github.com/jellyfin/cordova-plugin-chromecast.git" />`
in the config.xml

**Comment by Lindsay-Needs-Sleep** [comment]
This sounds like a problem with cocoa pods.

GoogleCast.h is part of the pod `google-cast-sdk-no-bluetooth` from Google.

You can try re-building the project from scratch.  (not sure if it is exactly the same as cordova)

- delete the `platforms`, `plugins`, and `node_modules` folders
- Re-run the build

If that doesn't fix it:

- You can check if the `google-cast-sdk-no-bluetooth` pod is present in the resulting iOS project
- You can check the build log (when you use phonegap to build) and look for cocoa pod related errors
- You might need to do some configuration on your mac to make the cocoa pods install work.  (I know I had some difficulty with this, eventually found some good advice on other cordova-plugin-xx's git issues.  Can;t remember where.)

**Comment by Lindsay-Needs-Sleep** [comment]
@Marthaarman  Were you able to get it working?

### If not, you can try this:  

From `/platforms/ios/` try running:    
```bash
sudo gem install cocoapods
pod repo update
pod install
```

### If the above doesn't work you can try this as well (low chance):

Try deleting all the derived data:
  * `rm -rf /Users/<username>/Library/Developer/Xcode/DerivedData/*`
  * restart Xcode
