### ISSUE TITLE
How to use it on Ionic 4?

### ISSUE THREAD

**Issue by julianCast** [jellyfin/cordova-plugin-chromecast#69]
Hi ! I'm having trouble importing chrome just to use it

These are my steps:
**INSTALL**: 
`cordova plugin add https://github.com/jellyfin/cordova-plugin-chromecast.git`

**USE** (This is probably the part Im doing wrong):
 `import * as Chrome from 'cordova-plugin-chromecast/www/chrome.cast';`

Log:
```
ERROR in ./node_modules/cordova-plugin-chromecast/www/chrome.cast.js
Module not found: Error: Can't resolve 'cordova-plugin-chromecast.EventEmitter' in 'E:\Github Projects\moodreads-ionic-4\node_modules\cordova-plugin-chromecast\www'
resolve 'cordova-plugin-chromecast.EventEmitter' in 'E:\Github Projects\moodreads-ionic-4\node_modules\cordova-plugin-chromecast\www'
  Parsed request is a module
  using description file: E:\Github Projects\moodreads-ionic-4\node_modules\cordova-plugin-chromecast\package.json (relative path: ./www)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in E:/Github Projects/moodreads-ionic-4
        using description file: E:\Github Projects\moodreads-ionic-4\package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: E:\Github Projects\moodreads-ionic-4\package.json (relative path: ./cordova-plugin-chromecast.EventEmitter)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\Github Projects\moodreads-ionic-4\cordova-plugin-chromecast.EventEmitter doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\Github Projects\moodreads-ionic-4\cordova-plugin-chromecast.EventEmitter.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              E:\Github Projects\moodreads-ionic-4\cordova-plugin-chromecast.EventEmitter.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              E:\Github Projects\moodreads-ionic-4\cordova-plugin-chromecast.EventEmitter.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\Github Projects\moodreads-ionic-4\cordova-plugin-chromecast.EventEmitter.js doesn't exist
            as directory
              E:\Github Projects\moodreads-ionic-4\cordova-plugin-chromecast.EventEmitter doesn't exist
```

Thanks!

**Comment by Lindsay-Needs-Sleep** [comment]
There is no ES6-like 'module' for chromecast.  (so you can't import it)

The cast object should just be present on the global `window` object.
eg. `window.chrome.cast.whateverFunction(....)`

Hopefully this is what you needed to know?

**Comment by julianCast** [comment]
I've used other modules as music-controls the same way, but it's true that in that case I have the typescript definitions. (https://github.com/ghenry22/cordova-plugin-music-controls2/blob/master/www/MusicControls.js)

My problem in this case is this line:
https://github.com/jellyfin/cordova-plugin-chromecast/blob/master/www/chrome.cast.js#L6
Just for testing I commented it and I'm able to access functions via Chrome.cast.whateverFunction().. (Obviously with a error caused by deleting EventEmitter variable).

But I'll try today your method using window.chrome... and let you know, thank you!

**Comment by julianCast** [comment]
> There is no ES6-like 'module' for chromecast. (so you can't import it)
> 
> The cast object should just be present on the global `window` object.
> eg. `window.chrome.cast.whateverFunction(....)`
> 
> Hopefully this is what you needed to know?

You are right! Now it's working! Thank you so much :)

**Comment by fitnexus** [comment]
hi, could you please share your code, i'm having the same issue. i've tried calling it using window.chrome but it doesn't get recognised
