### ISSUE TITLE
do you have an example of how to work with Media.seek?

### ISSUE THREAD

**Issue by mauricioruiz1997** [jellyfin/cordova-plugin-chromecast#70]
the following functions that comes in the example as
_media.pause ({}, function () { 
    });
,

_media.play({}, function () { 
    });

and 

_media.stop({}, function () { 
    });

works properly, but could not get the

_media.seek(

**Comment by Lindsay-Needs-Sleep** [comment]
Here is the documentation:
https://developers.google.com/cast/docs/reference/chrome/chrome.cast.media.Media.html#seek

Here is an example:  
```js
var request = new chrome.cast.media.SeekRequest();
request.currentTime = media.media.duration / 2;  // seek to 50%
media.seek(request, function () {
     // success
}, function (err) {
    // fail
});
```

**Comment by Lindsay-Needs-Sleep** [comment]
(You can find code examples of almost everything in the tests if the documentation doesn’t help.)

https://github.com/jellyfin/cordova-plugin-chromecast/blob/master/tests/www/js/tests_auto.js

**Comment by mauricioruiz1997** [comment]
thank you very much
