### ISSUE TITLE
[Question] Anybody found an event to detect when a track has ended playing?

### ISSUE THREAD

**Issue by julianCast** [jellyfin/cordova-plugin-chromecast#71]
Not an issue, but a question:

The only post I could find is this one https://stackoverflow.com/questions/19645972/chromecast-sdk-android-is-there-a-way-to-check-whether-the-media-playing-on but I wonder if any of you have used a different approach, it looks much for what it is.

The documentation has  https://developers.google.com/cast/docs/reference/chrome/chrome.cast.media.Media#addUpdateListener but does not provide such a action.

Thanks!

**Comment by Lindsay-Needs-Sleep** [comment]
You are on the right track with `media.addUpdateListener`.

You can see a bunch of example code in the [tests directory](https://github.com/jellyfin/cordova-plugin-chromecast/tree/master/tests/www/js) for this plugin (eg. [tests_auto.js](https://github.com/jellyfin/cordova-plugin-chromecast/blob/master/tests/www/js/tests_auto.js)).   
There is extra stuff going on there, but you might be able to figure out what you need for future things.

For detecting when a track has ended, this is what I used (simplified from the [tests_auto.js](https://github.com/jellyfin/cordova-plugin-chromecast/blob/master/tests/www/js/tests_auto.js)):

```js
media.addUpdateListener(function listener (isAlive) {
    if (media.playerState === chrome.cast.media.PlayerState.IDLE) {
        if (media.idleReason === chrome.cast.media.IdleReason.FINISHED) {
           // The current media has finished playing by reaching the end
        }
        if (media.idleReason === chrome.cast.media.IdleReason.CANCELLED) {
           // The current media has been stopped (media.stop)
        }
        if (media.idleReason === chrome.cast.media.IdleReason.INTERRUPTED) {
           // The current media has ended because new media has been loaded (media.queueJumpToItem)
        }
    }
});
```

Here is some of the relevant documentation:  
[playerState](https://developers.google.com/cast/docs/reference/chrome/chrome.cast.media#.PlayerState)
[idleReason](https://developers.google.com/cast/docs/reference/chrome/chrome.cast.media#.IdleReason)

**Comment by julianCast** [comment]
That is great, thank you again.
I was wrongly only using addUpdateListener  function from the session, not the media.

**Comment by Lindsay-Needs-Sleep** [comment]
Ahh, yep, easy mistake to make! 
np! 👍
