### ISSUE TITLE
Detect active session when re opening app + cast notification

### ISSUE THREAD

**Issue by esanchezvz** [jellyfin/cordova-plugin-chromecast#76]
This is isn't much of an issue, but it's a small bug I haven't been able to fix.
I'm building a feature to stream youtube video to a custom receiver. I've successfully managed to cast youtube videos to my custom receiver. However, whenever I start a cast session  and start streaming the video to a chromecast and close my app to do something else in my phone, the cast session is still active (which is the desired behaviour), but whenever I re-open my app I can't determine if a session is active already before initializing the cast SDK. 

I'm using Angular + Ionic. Here is my code, (Its not very elegant, but does the job haha)

```javascript
// cast.service.ts

@Injectable({
  providedIn: 'root',
})
export class CastService {
  videoId: string;
  startSeconds: number;
  receiverId = 'my-receiver';
  namespace = 'urn:x-cast:com.custom-namespace';
  castEnabled = false;
  isCasting = false;
  castSession: any;

  constructor() {}

  setParams({ videoId, startSeconds }: { videoId: string; startSeconds: number }) {
    this.videoId = videoId;
    this.startSeconds = startSeconds;
  }

  getCast() {
    return chrome.cast;
  }

  initCast() {
    const apiConfig = new chrome.cast.ApiConfig(
      new chrome.cast.SessionRequest(this.receiverId),
      (session: any) => {
        console.log(session);
        this.castSession = session;
      },
      function (receiverAvailable: any) {
        console.log(receiverAvailable);
      }
    );

    chrome.cast.initialize(
      apiConfig,
      () => {
        this.castEnabled = true;
        alert(JSON.stringify(this.castSession, null, 2));
      },
      (err: any) => {
        alert(JSON.stringify(err, null, 2));
      }
    );
  }

  requestSession(callback: Function) {
    // TODO Refactor callback into a cast status observer to subscribe on player
    chrome.cast.requestSession(
      (session: any) => {
        this.castSession = session;
        this.loadYoutubeVideo();
        callback();
        // alert(JSON.stringify(this.castSession));
      },
      (err: any) => {
        this.isCasting = false;
        this.castSession = null;
        callback();

        // if (err.code === 'cancel') return;
        // alert(JSON.stringify(err, null, 2));
      }
    );
  }

  stopSession() {
    this.castSession.stop(
      () => {
        this.isCasting = false;
        this.castSession = null;
      },
      (err: any) => {
        alert(JSON.stringify(err, null, 2));
      }
    );
  }

  private loadYoutubeVideo() {
    this.castSession.sendMessage(this.namespace, {
      command: 'INIT_COMMUNICATION_CONSTANTS',
      videoId: this.videoId,
      startSeconds: 0,
    });
    this.isCasting = true;
  }
}
```

```javascript
// youtube-player.component.ts

@Component({
  selector: 'app-youtube-player',
  templateUrl: './youtube-player.component.html',
  styleUrls: ['./youtube-player.component.scss'],
})
export class YoutubePlayerComponent implements OnInit {
  @Input() src: string;
  @ViewChild('player', { static: true }) player: ElementRef;
  loading: boolean = true;
  castButton: HTMLButtonElement;
  cast: any;

  constructor(public renderer: Renderer2, public castService: CastService) {}

  ngOnInit() {
    this.castService.setParams({ videoId: this.src, startSeconds: 0 });
    document.addEventListener('deviceready', () => {
      // Trying to determine if cast is already active
      this.cast = this.castService.getCast();
      alert(JSON.stringify(this.cast.SessionStatus, null, 2));

      // Initialize cast sdk
      this.castService.initCast();
    });

    this.renderer.setAttribute(this.player.nativeElement, 'data-plyr-provider', 'youtube');
    this.renderer.setAttribute(this.player.nativeElement, 'data-plyr-embed-id', this.src);

    const player = new Plyr(this.player.nativeElement, {
      controls: () => playerControls,
    });

    player.on('ready', (event) => {
      this.loading = false;
      this.castButton = <HTMLButtonElement>document.getElementById('castButton');
      this.castButton.addEventListener('click', (e) => {
        this.castService.requestSession(() => {
          this.castButton.blur(); // Loose focus to update DOM

          if (this.castService.isCasting) {
            this.castButton.innerHTML = castConnectedIcon;
          } else {
            this.castButton.innerHTML = castIcon;
          }
        });
      });

      if (!this.castService.castEnabled) {
        this.castButton.classList.add('disabled');
      } else {
        this.castButton.classList.remove('disabled');
        this.castButton.innerHTML = castIcon;
      }
    });
  }
}

```

Also, is it possible to show a push notification whenever I start casting with this plugin?

**Comment by Lindsay-Needs-Sleep** [comment]
Hi @esanchezvz 

The absolute earliest you can know if there is an active cast session (that your device can rejoin) is here:

```js

  initCast() {
    const apiConfig = new chrome.cast.ApiConfig(
      new chrome.cast.SessionRequest(this.receiverId),
      (session: any) => {
        // !HERE!  This is the earliest (and only) time that you can receiver a rejoined a cast session
       // this is only called when you rejoin a session.  It is not called when you create a brand new session.
        console.log(session);
        this.castSession = session;
      },
      function (receiverAvailable: any) {
        console.log(receiverAvailable);
      }
    );

    chrome.cast.initialize(
      apiConfig,
      () => {
        this.castEnabled = true;
        alert(JSON.stringify(this.castSession, null, 2));
      },
      (err: any) => {
        alert(JSON.stringify(err, null, 2));
      }
    );
  }
```
This is because initialize tells the app's native code what your recieverID is and then it looks a re-joinable session that is being cast to that receiver.

It might *technically* be possible for the native side to rejoin the session before calling initialize, but you would still have to wait for the `"deviceready"` event before you could communicate with the plugin to find out if you have a session anyways.  (And this wouldn't match the chrome desktop behavior [which is one of main design goals of this plugin).

---

I'm guessing you are asking this because it is kind of pain to manage the cast button state when you aren't sure if you are going to be rejoining a session or not?

If that is the case, my recommendation is doing something like this:  
(please forgive, I'm not familiar with ts.  Please look for all instances of `onSessionStateChangeListener`)
```js
export class CastService {
  videoId: string;
  startSeconds: number;
  receiverId = 'my-receiver';
  namespace = 'urn:x-cast:com.custom-namespace';
  castEnabled = false;
  isCasting = false;
  castSession: any;
  onSessionStateChangeListener: function;
  
  constructor() {}

  setParams({ videoId, startSeconds, onSessionStateChangeListener }: { videoId: string; startSeconds: number, onSessionStateChangeListener: function }) {
    this.videoId = videoId;
    this.startSeconds = startSeconds;
    this.onSessionStateChangeListener = onSessionStateChangeListener;
  }

  getCast() {
    return chrome.cast;
  }

  initCast() {
// Start out as unavailable
        this.onSessionStateChangeListener('UNAVAILABLE');
    const apiConfig = new chrome.cast.ApiConfig(
      new chrome.cast.SessionRequest(this.receiverId),
      (session: any) => {
        console.log(session);
        this.castSession = session;
        this.onSessionStateChangeListener('CASTING');
      },
      function (receiverAvailable: any) {
        console.log(receiverAvailable);
      }
    );

    chrome.cast.initialize(
      apiConfig,
      () => {
        this.castEnabled = true;
        alert(JSON.stringify(this.castSession, null, 2));
        this.onSessionStateChangeListener('INITIALIZED');
      },
      (err: any) => {
        alert(JSON.stringify(err, null, 2));
        this.onSessionStateChangeListener('UNAVAILABLE');
      }
    );
  }

  requestSession(callback: Function) {
        this.onSessionStateChangeListener('CONNECTING');
    // TODO Refactor callback into a cast status observer to subscribe on player
    chrome.cast.requestSession(
      (session: any) => {
        this.castSession = session;
        this.loadYoutubeVideo();
        this.onSessionStateChangeListener('CASTING');
        callback();
        // alert(JSON.stringify(this.castSession));
      },
      (err: any) => {
        this.isCasting = false;
        this.castSession = null;
        if (err.code === 'cancel') {
           this.onSessionStateChangeListener('INITIALIZED');
        } else {
           this.onSessionStateChangeListener('ERROR');  // Or 'INITIALIZED' so that the user can try again
        }
        callback();
        
        // alert(JSON.stringify(err, null, 2));
      }
    );
  }

  stopSession() {
    this.castSession.stop(
      () => {
        this.isCasting = false;
        this.castSession = null;
           this.onSessionStateChangeListener('INITIALIZED');
      },
      (err: any) => {
        alert(JSON.stringify(err, null, 2));
           this.onSessionStateChangeListener('ERROR'); // Or 'INITIALIZED' not actually sure when this error would happen, but it is probably okay to let the user to continue using cast
      }
    );
  }

  private loadYoutubeVideo() {
    this.castSession.sendMessage(this.namespace, {
      command: 'INIT_COMMUNICATION_CONSTANTS',
      videoId: this.videoId,
      startSeconds: 0,
    });
    this.isCasting = true;
  }
}
```

Then you just have to do something potentiall like:
```js
// youtube-player.component.ts
...
  ngOnInit() {
	this.castService.setParams({ 
                videoId: this.src, 
                startSeconds: 0,  
		onSessionStateChangeListener: function (castState) {
			switch (castState) {
				case 'UNAVAILABLE':	
					// Cast button should probably be hidden:
					// at this point we don't know of any available chrome cast devices
					break;
				case 'INITIALIZED':
					// Show cast button, make it clickable
					break;
				case 'CONNECTING':
					// Maybe show grey cast button to indicate loading? disable clicks maybe
					break;
				case 'CASTING':
					// Make cast button show that it is casting
					break;
				case 'ERROR':
					// Maybe revert button to INITIALIZED of CASTING if you want user to be able to retry whatever they were doing
					// Or disable the button, your call
					// Or maybe never use the 'ERROR' state at all in cast.service.ts
					break;
			}
		}
	});
    document.addEventListener('deviceready', () => {
      // Trying to determine if cast is already active
      this.cast = this.castService.getCast();
      alert(JSON.stringify(this.cast.SessionStatus, null, 2));

      // Initialize cast sdk
      this.castService.initCast();
    });
...
```

If you use an event / state driven system like this, then you don't have to care about how or when you got the session.  

You can expand this to include a 'PLAYING' state as well if you need it.  Check if `session.media && session.media[0] && session.media[0].playerState` is one of `[chrome.cast.media.PlayerState.PLAYING, chrome.cast.media.PlayerState.BUFFERING]`

**Comment by Lindsay-Needs-Sleep** [comment]
As for the push notification, you would need to use another cordova plugin to send one out.  Probably [cordova-plugin-push](https://github.com/havesource/cordova-plugin-push)?  Disclaimer: I haven't used it myself.

---

Although maybe you are talking about this:  
When I am doing cast work, my family get notifications on some of their **Android** devices everytime I start casting.  Not actually sure how this happens.  I think they might have to have the **Google Home** app installed (and maybe have hooked up to the chrome cast device before).

**Comment by esanchezvz** [comment]
Thank you so much for your response! It was very helpful as I'm not that experienced in mobile development and have never worked with Google Cast before.
And I will look into doing this with state/event driven approach.

The app that I'm building is actually for testing purposes so we can determine whether or not to include this feature in our app and what the best integration with our codebase would be.

> I'm guessing you are asking this because it is kind of pain to manage the cast button state when you aren't sure if you are going to be rejoining a session or not?

That's exactly why I want to do this. And also to determine whether or I not I should render an overlay on top of the video player that has the controls (play/pause and mute) that communicate to the receiver

<hr/>

As far as the push notification, what I want to know if it's possible to achieve is show a push notification that can't be dismissed  whenever my app is casting that shows some basic controls like pause and cancel session. I mean, this is definitely not a must have but would be very nice to have so I don't break the current app's UI by adding the cast button to be visible on every screen so the user can stop casting anytime they choose to.

Anyways, thank you again for your response and also this plugin which really made it a lot easier to integrate Cast into my app.

**Comment by Lindsay-Needs-Sleep** [comment]
Ooh I see what you mean for the push notifications!

That is a cool idea!  This plugin definitely doesn’t have that capability though. xD

Is it possible to make push notifications that can’t be closed?

If it is, then it might be possible to add something like that to this plugin.  (But it’s probably easier to just add the cast button to your html/js etc. :p)

Android can definitely control the cast from a notification.  (You can see my fork of cordova-plugin-chromecast at miloproductionsinc, and I have a [branch with 1 additional commit where I was playing with customizing the push notification](https://github.com/miloproductionsinc/cordova-plugin-chromecast/commit/dc8a9f79199aad965ff481f8be5a6ff0aa113c3c).)  I’m also not sure if the push notification stays active and functioning after the app has been closed.  The push notification also only happens on  newer-ish android OS (not sure what the cut off is, I think it works for my 6.x device and not 4.4).

I don’t know if this is possible on iOS though.  I don’t think you can control anything from push notifications on iOS.  They do have some kind of option for controlling from the lock screen though (I think).

PS. Thanks for nice words. :)
