### ISSUE TITLE
Android Receiver discrepancies after Restart

### ISSUE THREAD

**Issue by edmundpf** [jellyfin/cordova-plugin-chromecast#80]
I'm seeing some strange behavior that only happens on Android that i'm completely stuck on. 

I do the following, I initialize a default media receiver, and I see that the receiver is available. I cast to the device successfully, and let the user stop the cast.

When the cast is stopped, if the user closes the app, removing it from the background apps by swiping to close, then the next time they open the app, the receiver will not become available. If they close it this way again, the receiver will be available this time. I can repeat this process in a pattern. Super frustrating, is there someway to reset the chrome.cast instance or something?

I am 100% sure I have no logic to cause this. Works completely fine every time on iOS and web.

Any help would be greatly appreciated.

**Comment by edmundpf** [comment]
Wow. To anyone reading this, please save yourself a full day of debugging, on android you must stop the media BEFORE stopping the session. On iOS you can just stop the session without stopping the media and it does not matter. If you only stop the session this weird bug will occur. Save yourself, godspeed.

**Comment by Lindsay-Needs-Sleep** [comment]
That is interesting behavior. :/

To confirm:  
* on Android
* play some media
* User triggers session.stop()?
* force quit app
* open app 
  * the session is NOT resumed?
* force quit app
   * the session IS resumed?
   
@edmundpf Could you possible copy the list above and add annotation to the points that have `?` to confirm?

Also just want to confirm if you are using the newest version on: https://github.com/miloproductionsinc/cordova-plugin-chromecast (there are a couple bug fixes and improvements there).

**Comment by edmundpf** [comment]
> That is interesting behavior. :/
> 
> To confirm:
> 
> * on Android
> * play some media
> * User triggers session.stop()?
> * force quit app
> * open app
>   
>   * the session is NOT resumed?
> * force quit app
>   
>   * the session IS resumed?
> 
> @edmundpf Could you possible copy the list above and add annotation to the points that have `?` to confirm?
> 
> Also just want to confirm if you are using the newest version on: https://github.com/miloproductionsinc/cordova-plugin-chromecast (there are a couple bug fixes and improvements there).

I was using the jellyfin repo, I wasn't aware of the newer fork but can try that as well.

* The user triggers session.stop(), correct
* Force quit app
* Session is not resumed, and the receiverListener callback inside of ApiConfig will never return an available receiver, it will simply return 'unavailable'
* After next force quit, session is not resumed, but the receiverListener callback inside of ApiConfig will return an available receiver

``` javascript
var apiConfig = new chrome.cast.ApiConfig(new chrome.cast.SessionRequest(appId), function sessionListener (session) {

            }, function receiverListener (receiverAvailable) {
                // Returns 'available' on first run, until user calls 'session.stop()'
                // After force quit, this always returns 'unavailable'
                // After another force quit, will now return 'available' again until user calls 'session.stop()'
                // This process repeats on android only
            });
```

Let me know if there's anything else I can clarify.

**Comment by Lindsay-Needs-Sleep** [comment]
@edmundpf  Thanks for the feedback!

If this this still happens on the newer version can you let me know?  (It probably does, but maybe not)
If I ever get time to work on this again, the more info I have the easier. :D

By any chance was this behavior on an older Android device?  Maybe 4.4 or 5.0?

I seem to remember spending a full day fighting a really weird issue on android 4.4 that was something similar....  Unfortunately, the result was that there was a bug deep inside the chromecast library that I had no power to change or work around....

**Comment by Lindsay-Needs-Sleep** [comment]
Actually, it looks pretty darn similar to the error I found (maybe the same).  (though you aren't doing anything with shared sessions?)
https://github.com/miloproductionsinc/cordova-plugin-chromecast/issues/7 

It has been over a year since I encountered that issue, and I have updated the chromecast SDK, so maybe -*hopefully* that has fixed it.

**Comment by edmundpf** [comment]
> miloproductionsinc#7

That looks very similar indeed, it was an Android 5.1 so definitely older, I'll let you know if I encounter it on the updated repo!
